/**
 * transaction-mock.data.ts
 *
 * Mock data dùng để phát triển và kiểm tra giao diện Transaction.
 * File này CHỈ được import khi useMockTransactions = true trong environment.
 * Không ảnh hưởng đến production build khi cờ được tắt.
 */

import { TransactionDto } from '../../../models/transaction.dto';

// Ngày hiện tại để tính toán các mốc thời gian tương đối
const now = new Date();
const d = (daysAgo: number, hour = 10, min = 0): string => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() - daysAgo);
  dt.setHours(hour, min, 0, 0);
  return dt.toISOString();
};

export const TRANSACTION_MOCK_DATA: TransactionDto[] = [
  // ─── Hôm nay ────────────────────────────────────────────────────────────────
  {
    id: 1001,
    name: 'Bún bò Huế Cô Ba',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 55000,
    transactionDate: d(0, 8, 15),
    status: 1,
    isAiEstimated: false,
    createdAt: d(0, 8, 16),
    note: 'Ăn sáng trước khi đi làm',
    paymentMethod: 'cash',
    source: 'manual',
    transactionDetails: [
      {
        id: 10011,
        transactionId: 1001,
        categoryId: 1,
        itemName: 'Bún bò đặc biệt',
        categoryName: 'food',
        price: 55000,
        quantity: 1,
        unit: 'tô',
        estimatedCalories: 520,
      },
    ],
  },
  {
    id: 1002,
    name: 'Highlands Coffee',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 75000,
    transactionDate: d(0, 10, 30),
    status: 1,
    isAiEstimated: false,
    createdAt: d(0, 10, 31),
    note: null,
    paymentMethod: 'ewallet',
    source: 'snap',
    transactionDetails: [
      {
        id: 10021,
        transactionId: 1002,
        categoryId: 2,
        itemName: 'Freeze Trà Xanh size L',
        categoryName: 'drinks',
        price: 75000,
        quantity: 1,
        unit: 'ly',
        estimatedCalories: 380,
      },
    ],
  },
  {
    id: 1003,
    name: 'Grab Bike – Q1 → Q3',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 32000,
    transactionDate: d(0, 12, 5),
    status: 1,
    isAiEstimated: false,
    createdAt: d(0, 12, 6),
    note: 'Đi họp công ty',
    paymentMethod: 'ewallet',
    source: 'manual',
    transactionDetails: [
      {
        id: 10031,
        transactionId: 1003,
        categoryId: 5,
        itemName: 'Grab Bike',
        categoryName: 'travel',
        price: 32000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },

  // ─── Hôm qua ─────────────────────────────────────────────────────────────────
  {
    id: 1004,
    name: 'VinMart – Siêu thị',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 312000,
    transactionDate: d(1, 18, 45),
    status: 1,
    isAiEstimated: true,
    createdAt: d(1, 18, 47),
    note: 'Mua đồ ăn cả tuần',
    paymentMethod: 'creditcard',
    source: 'receipt',
    transactionDetails: [
      {
        id: 10041,
        transactionId: 1004,
        categoryId: 3,
        itemName: 'Thịt heo ba chỉ 500g',
        categoryName: 'food',
        price: 89000,
        quantity: 1,
        unit: 'gói',
        estimatedCalories: null,
      },
      {
        id: 10042,
        transactionId: 1004,
        categoryId: 3,
        itemName: 'Rau củ hỗn hợp',
        categoryName: 'food',
        price: 45000,
        quantity: 1,
        unit: 'túi',
        estimatedCalories: null,
      },
      {
        id: 10043,
        transactionId: 1004,
        categoryId: 3,
        itemName: 'Trứng gà ta',
        categoryName: 'food',
        price: 38000,
        quantity: 2,
        unit: 'vỉ',
        estimatedCalories: null,
      },
      {
        id: 10044,
        transactionId: 1004,
        categoryId: 3,
        itemName: 'Nước mắm Phú Quốc',
        categoryName: 'food',
        price: 52000,
        quantity: 1,
        unit: 'chai',
        estimatedCalories: null,
      },
      {
        id: 10045,
        transactionId: 1004,
        categoryId: 3,
        itemName: 'Sữa tươi Vinamilk',
        categoryName: 'food',
        price: 88000,
        quantity: 2,
        unit: 'hộp',
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1005,
    name: 'Netflix Premium',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 260000,
    transactionDate: d(1, 9, 0),
    status: 1,
    isAiEstimated: false,
    createdAt: d(1, 9, 1),
    note: 'Gia hạn tháng 7',
    paymentMethod: 'creditcard',
    source: 'manual',
    transactionDetails: [
      {
        id: 10051,
        transactionId: 1005,
        categoryId: 6,
        itemName: 'Netflix Premium Plan',
        categoryName: 'bill',
        price: 260000,
        quantity: 1,
        unit: 'tháng',
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1006,
    name: 'Shopee – Áo thun',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 189000,
    transactionDate: d(1, 14, 22),
    status: 0,
    isAiEstimated: false,
    createdAt: d(1, 14, 23),
    note: 'Đang chờ giao hàng',
    paymentMethod: 'banktransfer',
    source: 'manual',
    transactionDetails: [
      {
        id: 10061,
        transactionId: 1006,
        categoryId: 7,
        itemName: 'Áo thun basic oversize',
        categoryName: 'other',
        price: 189000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },

  // ─── 3 ngày trước ─────────────────────────────────────────────────────────────
  {
    id: 1007,
    name: 'Phở Thìn – Bữa trưa',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 80000,
    transactionDate: d(3, 11, 50),
    status: 1,
    isAiEstimated: false,
    createdAt: d(3, 11, 51),
    note: null,
    paymentMethod: 'cash',
    source: 'snap',
    transactionDetails: [
      {
        id: 10071,
        transactionId: 1007,
        categoryId: 1,
        itemName: 'Phở tái đặc biệt',
        categoryName: 'food',
        price: 80000,
        quantity: 1,
        unit: 'tô',
        estimatedCalories: 650,
      },
    ],
  },
  {
    id: 1008,
    name: 'Tiền điện tháng 6',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 485000,
    transactionDate: d(3, 8, 0),
    status: 1,
    isAiEstimated: false,
    createdAt: d(3, 8, 1),
    note: 'Thanh toán qua app EVN',
    paymentMethod: 'banktransfer',
    source: 'manual',
    transactionDetails: [
      {
        id: 10081,
        transactionId: 1008,
        categoryId: 8,
        itemName: 'Hóa đơn điện tháng 6',
        categoryName: 'bill',
        price: 485000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1009,
    name: 'Circle K – Đồ uống',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 47000,
    transactionDate: d(3, 16, 40),
    status: 2,
    isAiEstimated: false,
    createdAt: d(3, 16, 41),
    note: 'Giao dịch thất bại – thẻ từ chối',
    paymentMethod: 'debitcard',
    source: 'manual',
    transactionDetails: [
      {
        id: 10091,
        transactionId: 1009,
        categoryId: 2,
        itemName: 'Nước tăng lực Monster',
        categoryName: 'drinks',
        price: 25000,
        quantity: 1,
        unit: 'lon',
        estimatedCalories: 190,
      },
      {
        id: 10092,
        transactionId: 1009,
        categoryId: 2,
        itemName: 'Sandwich gà',
        categoryName: 'food',
        price: 22000,
        quantity: 1,
        unit: null,
        estimatedCalories: 320,
      },
    ],
  },

  // ─── 5 ngày trước ─────────────────────────────────────────────────────────────
  {
    id: 1010,
    name: 'CGV – Xem phim',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 160000,
    transactionDate: d(5, 19, 30),
    status: 1,
    isAiEstimated: false,
    createdAt: d(5, 19, 31),
    note: 'Ưu đãi thứ 4 – 2 vé',
    paymentMethod: 'creditcard',
    source: 'manual',
    transactionDetails: [
      {
        id: 10101,
        transactionId: 1010,
        categoryId: 9,
        itemName: 'Vé xem phim CGV',
        categoryName: 'other',
        price: 80000,
        quantity: 2,
        unit: 'vé',
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1011,
    name: 'Techcombank – Phí dịch vụ',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 11000,
    transactionDate: d(5, 7, 0),
    status: 1,
    isAiEstimated: false,
    createdAt: d(5, 7, 0),
    note: null,
    paymentMethod: 'banktransfer',
    source: 'manual',
    transactionDetails: [
      {
        id: 10111,
        transactionId: 1011,
        categoryId: 10,
        itemName: 'Phí SMS banking tháng 7',
        categoryName: 'bill',
        price: 11000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },

  // ─── 7 ngày trước ─────────────────────────────────────────────────────────────
  {
    id: 1012,
    name: 'The Coffee House',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 95000,
    transactionDate: d(7, 15, 20),
    status: 1,
    isAiEstimated: true,
    createdAt: d(7, 15, 22),
    note: 'Họp với khách hàng',
    paymentMethod: 'ewallet',
    source: 'snap',
    transactionDetails: [
      {
        id: 10121,
        transactionId: 1012,
        categoryId: 2,
        itemName: 'Cold Brew Sữa',
        categoryName: 'drinks',
        price: 55000,
        quantity: 1,
        unit: 'ly',
        estimatedCalories: 210,
      },
      {
        id: 10122,
        transactionId: 1012,
        categoryId: 2,
        itemName: 'Bánh mì bơ tỏi',
        categoryName: 'food',
        price: 40000,
        quantity: 1,
        unit: null,
        estimatedCalories: 280,
      },
    ],
  },
  {
    id: 1013,
    name: 'Cơm tấm Thuận Kiều',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 45000,
    transactionDate: d(7, 12, 0),
    status: 3,
    isAiEstimated: false,
    createdAt: d(7, 12, 1),
    note: 'Huỷ do nhầm địa chỉ',
    paymentMethod: 'cash',
    source: 'manual',
    transactionDetails: [
      {
        id: 10131,
        transactionId: 1013,
        categoryId: 1,
        itemName: 'Cơm tấm sườn bì chả',
        categoryName: 'food',
        price: 45000,
        quantity: 1,
        unit: 'phần',
        estimatedCalories: 720,
      },
    ],
  },

  // ─── 10 ngày trước ────────────────────────────────────────────────────────────
  {
    id: 1014,
    name: 'Thegioididong – Cáp sạc',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 199000,
    transactionDate: d(10, 17, 0),
    status: 1,
    isAiEstimated: false,
    createdAt: d(10, 17, 2),
    note: 'Cáp USB-C cho iPhone 15',
    paymentMethod: 'debitcard',
    source: 'receipt',
    transactionDetails: [
      {
        id: 10141,
        transactionId: 1014,
        categoryId: 11,
        itemName: 'Cáp sạc Anker USB-C 1m',
        categoryName: 'electronics',
        price: 199000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1015,
    name: 'Tiền nước tháng 6',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 98000,
    transactionDate: d(10, 9, 30),
    status: 1,
    isAiEstimated: false,
    createdAt: d(10, 9, 31),
    note: null,
    paymentMethod: 'banktransfer',
    source: 'manual',
    transactionDetails: [
      {
        id: 10151,
        transactionId: 1015,
        categoryId: 8,
        itemName: 'Hóa đơn nước tháng 6',
        categoryName: 'bill',
        price: 98000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },

  // ─── 14 ngày trước ────────────────────────────────────────────────────────────
  {
    id: 1016,
    name: 'Bánh mì Huỳnh Hoa',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 40000,
    transactionDate: d(14, 7, 45),
    status: 1,
    isAiEstimated: false,
    createdAt: d(14, 7, 46),
    note: null,
    paymentMethod: 'cash',
    source: 'manual',
    transactionDetails: [
      {
        id: 10161,
        transactionId: 1016,
        categoryId: 1,
        itemName: 'Bánh mì thịt đặc biệt',
        categoryName: 'food',
        price: 40000,
        quantity: 1,
        unit: null,
        estimatedCalories: 410,
      },
    ],
  },
  {
    id: 1017,
    name: 'Spotify Premium',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 59000,
    transactionDate: d(14, 10, 0),
    status: 0,
    isAiEstimated: false,
    createdAt: d(14, 10, 1),
    note: 'Đang chờ xác nhận thanh toán',
    paymentMethod: 'creditcard',
    source: 'manual',
    transactionDetails: [
      {
        id: 10171,
        transactionId: 1017,
        categoryId: 6,
        itemName: 'Spotify Premium Individual',
        categoryName: 'bill',
        price: 59000,
        quantity: 1,
        unit: 'tháng',
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1018,
    name: 'Xe bus BRT – Đi lại',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 15000,
    transactionDate: d(14, 8, 30),
    status: 1,
    isAiEstimated: false,
    createdAt: d(14, 8, 31),
    note: 'Vé tháng xe bus',
    paymentMethod: 'ewallet',
    source: 'manual',
    transactionDetails: [
      {
        id: 10181,
        transactionId: 1018,
        categoryId: 5,
        itemName: 'Vé xe bus BRT',
        categoryName: 'travel',
        price: 15000,
        quantity: 1,
        unit: 'lượt',
        estimatedCalories: null,
      },
    ],
  },

  // ─── 20 ngày trước ────────────────────────────────────────────────────────────
  {
    id: 1019,
    name: 'IKEA – Nội thất',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 1250000,
    transactionDate: d(20, 14, 0),
    status: 1,
    isAiEstimated: true,
    createdAt: d(20, 14, 5),
    note: 'Mua giá sách và đèn bàn',
    paymentMethod: 'creditcard',
    source: 'receipt',
    transactionDetails: [
      {
        id: 10191,
        transactionId: 1019,
        categoryId: 12,
        itemName: 'Giá sách KALLAX 2×2',
        categoryName: 'household',
        price: 850000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
      {
        id: 10192,
        transactionId: 1019,
        categoryId: 12,
        itemName: 'Đèn bàn FORSÅ',
        categoryName: 'household',
        price: 400000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },
  {
    id: 1020,
    name: 'Bác sĩ thú y – Mèo Cam',
    userId: 'mock-user',
    imageKey: null,
    imagePreviewUrl: null,
    totalAmount: 320000,
    transactionDate: d(20, 10, 0),
    status: 1,
    isAiEstimated: false,
    createdAt: d(20, 10, 2),
    note: 'Tiêm phòng và khám định kỳ',
    paymentMethod: 'cash',
    source: 'manual',
    transactionDetails: [
      {
        id: 10201,
        transactionId: 1020,
        categoryId: 13,
        itemName: 'Tiêm phòng dại',
        categoryName: 'animals',
        price: 180000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
      {
        id: 10202,
        transactionId: 1020,
        categoryId: 13,
        itemName: 'Phí khám thú y',
        categoryName: 'animals',
        price: 140000,
        quantity: 1,
        unit: null,
        estimatedCalories: null,
      },
    ],
  },
];
